from enum import StrEnum

class HttpHeaders(StrEnum):
    # General Headers
    CACHE_CONTROL = "Cache-Control"
    CONNECTION = "Connection"
    CONTENT_LENGTH = "Content-Length"
    CONTENT_TYPE = "Content-Type"
    DATE = "Date"
    PRAGMA = "Pragma"
    VIA = "Via"
    WARNING = "Warning"
    
    # Request Headers
    ACCEPT = "Accept"
    ACCEPT_CHARSET = "Accept-Charset"
    ACCEPT_ENCODING = "Accept-Encoding"
    ACCEPT_LANGUAGE = "Accept-Language"
    AUTHORIZATION = "Authorization"
    COOKIE = "Cookie"
    EXPECT = "Expect"
    FROM = "From"
    HOST = "Host"
    IF_MATCH = "If-Match"
    IF_MODIFIED_SINCE = "If-Modified-Since"
    IF_NONE_MATCH = "If-None-Match"
    IF_RANGE = "If-Range"
    IF_UNMODIFIED_SINCE = "If-Unmodified-Since"
    ORIGIN = "Origin"
    PROXY_AUTHORIZATION = "Proxy-Authorization"
    RANGE = "Range"
    REFERER = "Referer"
    TE = "TE"
    USER_AGENT = "User-Agent"
    UPGRADE = "Upgrade"
    X_FORWARDED_FOR = "X-Forwarded-For"
    X_REAL_IP = "X-Real-IP"
    
    # Response Headers
    ACCEPT_RANGES = "Accept-Ranges"
    ACCESS_CONTROL_ALLOW_ORIGIN = "Access-Control-Allow-Origin"
    ACCESS_CONTROL_ALLOW_METHODS = "Access-Control-Allow-Methods"
    ACCESS_CONTROL_ALLOW_HEADERS = "Access-Control-Allow-Headers"
    ACCESS_CONTROL_EXPOSE_HEADERS = "Access-Control-Expose-Headers"
    ACCESS_CONTROL_MAX_AGE = "Access-Control-Max-Age"
    AGE = "Age"
    ALLOW = "Allow"
    CONTENT_DISPOSITION = "Content-Disposition"
    CONTENT_ENCODING = "Content-Encoding"
    CONTENT_LANGUAGE = "Content-Language"
    CONTENT_LOCATION = "Content-Location"
    CONTENT_RANGE = "Content-Range"
    ETAG = "ETag"
    EXPIRES = "Expires"
    LAST_MODIFIED = "Last-Modified"
    LINK = "Link"
    LOCATION = "Location"
    PROXY_AUTHENTICATE = "Proxy-Authenticate"
    RETRY_AFTER = "Retry-After"
    SERVER = "Server"
    SET_COOKIE = "Set-Cookie"
    STRICT_TRANSPORT_SECURITY = "Strict-Transport-Security"
    TRAILER = "Trailer"
    TRANSFER_ENCODING = "Transfer-Encoding"
    VARY = "Vary"
    WWW_AUTHENTICATE = "WWW-Authenticate"
    
    # WebSockets Headers
    SEC_WEBSOCKET_ACCEPT = "Sec-WebSocket-Accept"
    SEC_WEBSOCKET_EXTENSIONS = "Sec-WebSocket-Extensions"
    SEC_WEBSOCKET_KEY = "Sec-WebSocket-Key"
    SEC_WEBSOCKET_PROTOCOL = "Sec-WebSocket-Protocol"
    SEC_WEBSOCKET_VERSION = "Sec-WebSocket-Version"
    
    # CORS Specific Headers
    ACCESS_CONTROL_REQUEST_METHOD = "Access-Control-Request-Method"
    ACCESS_CONTROL_REQUEST_HEADERS = "Access-Control-Request-Headers"
    
    # Deprecated/Legacy Headers (for reference)
    X_CONTENT_TYPE_OPTIONS = "X-Content-Type-Options"
    X_FRAME_OPTIONS = "X-Frame-Options"
    X_XSS_PROTECTION = "X-XSS-Protection"
    X_POWERED_BY = "X-Powered-By"
    X_UA_COMPATIBLE = "X-UA-Compatible"
